//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ServiceModel;
using System.Runtime.Serialization;

namespace wsEmployees.dao
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class NhanVien
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public string address { get; set; }
    }
}
